project_id = "lkjylvrhwebxyahzblfl"

[functions.parse-handoff]
verify_jwt = false

[functions.parse-single-patient]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.transform-text]
verify_jwt = false

[functions.generate-todos]
verify_jwt = false

[functions.format-medications]
verify_jwt = false
